#缓存服务
server:
  port: 1001
  context-path: /wq-cache

#redis配置
spring:
  redis:
    database: 0 #用16个库中索引为0的库
    host: 127.0.0.1 #redis服务器的主机IP
    port: 6379      #redis的端口
    password:       #密码,默认为空
    timeout: 1000   #连接超时时间,单位为毫秒
    pool:
      max-active: 200   #连接池的最大连接数,当为负数的时候表示没有限制
      max-wait: -1      #连接池的最大阻塞等待时间,为负数的时候表示没有限制
      max-idle: 10      #连接池的最大空闲连接
      min-idle: 0       #连接池的最小的空闲连接